config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  devise_scope :user do
    authenticated do
      root 'profiles#home', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  resources :expenses
  get '/ungrouped', to: 'expenses#ungrouped'
  resources :groups

  get '/members', to: 'profiles#members'

  match ':not_found' => redirect('/'), constraints: { :not_found => /.*/ }, via: [:get, :post]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  validates :name, presence: true
  validates_numericality_of :amount, greater_than: 0, numericality: true

  belongs_to :user
  has_many :expense_groups
  has_many :groups, through: :expense_groups

  scope :total_amount, -> { sum(:amount) }

  scope :none_grouped_expenses, -> { where('expenses.id NOT IN (?)', ExpenseGroup.distinct.pluck(:expense_id)) }
end

app/models/expense_group.rb
class ExpenseGroup < ApplicationRecord
  belongs_to :expense
  belongs_to :group
end

app/models/group.rb
class Group < ApplicationRecord
  validates :name, presence: true, uniqueness: { case_sensitive: false }

  belongs_to :user
  has_many :expense_groups
  has_many :expenses, through: :expense_groups
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  valid_email = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :name, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 25 }
  validates :email, presence: true, length: { maximum: 105 }, uniqueness: { case_sensitive: false }, format: { with: valid_email }
  validates :password_confirmation, :password, presence: true, length: { minimum: 6, maximum: 40 }

  has_many :expenses
  has_many :groups
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :user_expenses, except: [:destroy]

  def index
    @expenses_amount = @expenses.total_amount
  end

  def destroy
    expense = Expense.find_by_id(params[:id])

    respond_to do |format|
      if expense.destroy
        format.html { redirect_to expenses_path, notice: 'Expense was deleted successfuly' }
      else
        format.html { render 'index' }
      end
    end
  end

  def new
    @expense = Expense.new
    @user_groups = current_user.groups
  end

  def create
    expense = @expenses.new(expense_params)

    respond_to do |format|
      if expense.save
        format.html { redirect_to expenses_path, notice: 'Expense was created successfuly' }
      else
        format.html { render 'new' }
      end
    end
  end

  def ungrouped
    @ungrouped_expenses = @expenses.none_grouped_expenses
    @ungrouped_amount = @ungrouped_expenses.total_amount
  end

  private

  def user_expenses
    @expenses = current_user.expenses
  end

  def expense_params
    params.require(:expense).permit(:name, :amount, :user_id, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]

  def index
    @groups = current_user.groups
  end

  def new
    @group = Group.new
  end

  def show
    @group_expenses = @group.expenses
    @group_amount = @group_expenses.total_amount
  end

  def destroy
    respond_to do |format|
      if @group.destroy
        format.html { redirect_to groups_path, notice: 'Group was deleted successfuly' }
      else
        format.html { render 'index' }
      end
    end
  end

  def edit; end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to groups_path, notice: 'Group was updated successfuly' }
      else
        format.html { render 'edit' }
      end
    end
  end

  def create
    group = current_user.groups.new(group_params)

    respond_to do |format|
      if group.save
        format.html { redirect_to groups_path, notice: 'Group was created successfuly' }
      else
        format.html { render 'new' }
      end
    end
  end

  private

  def set_group
    @group = Group.find_by_id(params[:id])
  end

  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def home; end

  def members
    @members = User.all
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end

  def acount_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end

  def after_sign_up_path_for(_resource)
    '/'
  end

  def after_sign_in_path_for(_resource)
    '/'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/expenses/_form.html.erb
<%= simple_form_for(@expense) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true, input_html: { class: 'form-control' }, label_html: { class: 'text-dark h4' } %>
    <%= f.input :amount,required: true, input_html: { class: 'form-control' }, label_html: { class: 'text-dark h4' } %>

    <fieldset class='checkboxs'>
    <%= f.collection_check_boxes :group_ids, @user_groups, :id, :name do |cb| %>
      <%= cb.label(class: "checkbox-inline input_checkbox") {cb.check_box(class: "checkbox") + cb.text} %>
    <% end %>
    </fieldset>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/expenses/index.html.erb
<h1 class='expenses-title'>Expenses</h1>

<div class='details'>
  <h3>Total amount</h3>
  <h3>$<%= @expenses_amount %></h3>
</div>

<%= render partial: 'shared/expense', collection: @expenses %>

<%= link_to 'Add New Transaction', new_expense_path, class: 'btn btn-success' %>

app/views/expenses/new.html.erb
<%= render 'form', expense: @expense %>

app/views/expenses/ungrouped.html.erb
<h1 class='expenses-title'>Ungrouped expenses</h1>

<div class='details'>
  <h3>Total amount</h3>
  <h3>$<%= @ungrouped_amount %></h3>
</div>

<%= render partial: 'shared/expense', collection: @ungrouped_expenses %>

<%= link_to 'Add New Transaction', new_expense_path, class: 'btn btn-success' %>

app/views/groups/_form.html.erb
<%= simple_form_for(@group) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name, required: true, input_html: { class: 'form-control' }, label_html: { class: 'text-dark h4' } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-success btn-block' %>
  </div>
<% end %>

app/views/groups/edit.html.erb
<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<h1 class='groups-title'>Groups</h1>

<ul class='groups-list'>
  <% @groups.each do |group| %>
    <li>
      <%= link_to group_path(group.id), class: 'group' do %>
        <span><%= group.name %></span>
        <span><%= time_ago_in_words(group.created_at) %> ago</span>
        <%= link_to 'Delete', group_path(group), method: :delete, data: {confirm: 'Are you sure?'}, class:'delete' %>
      <% end %>
    </li>
  <% end %>
</ul>

<%= link_to "Add New Group", new_group_path, class: 'btn btn-success new-group' %>

app/views/groups/new.html.erb
<h1 class='groups-title'>Add new group</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<div class='details'>
  <h3><%= @group.name %></h3>
  <h3>Total amount: $<%= @group_amount %></h3>
</div>

<h2 class='text-center'>Belongs Expenses</h2>

<%= render partial: 'shared/expense', collection: @group_expenses %>

<%= link_to 'Edit', edit_group_path, class: 'btn btn-danger' %>
<%= link_to 'Add New Transaction', new_expense_path, class: 'btn btn-success' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ExpensesRegulator</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= render partial: 'shared/nav' %>
    <%= yield %>
  </body>
</html>

app/views/profiles/home.html.erb
<div class='background'>
  <h1 class='text-center welcome'>Welcome: <%= current_user.name %></h1>
  <div class='home-links'>
    <%= link_to 'groups', groups_path, class:'home-link' %>
    <%= link_to 'ungrouped expenses', ungrouped_path, class:'home-link' %>
    <%= link_to 'All expenses', expenses_path, class:'home-link' %>
    <%= link_to 'Members', members_path, class:'home-link' %>
  </div>
  <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'form-control btn btn-danger' %>
</div>

app/views/profiles/members.html.erb
<h1 class='text-center'>Members total expenses</h1>

<% @members.each do |member| %>
  <ul class='details'>
    <li><%= member.name %></li>
    <li>$<%= member.expenses.total_amount %></li>
  </ul>
<% end %>

app/views/shared/_expense.html.erb
<ul class='details'>
  <li>amount <h4>$<%= expense.amount %></h4></li>
  <li>name<h4><%= expense.name %></h4></li>
  <li><%= link_to 'Delete', expense_path(expense), method: :delete, data: {confirm: 'Are you sure?'}, class:'delete' %></li>
</ul>

app/views/shared/_nav.html.erb
<nav class='navbar'>
  <a href=<%= authenticated_root_path %> class='logo'>
    <img src="<%= asset_path( 'money.svg' ) %>" height='30' width='40' />
    ExpensesRegulator
  </a>
  <a href=<%=authenticated_root_path%> class='burger'>
    <span></span>
    <span></span>
    <span></span>
  </a>
</nav>